version: '2'

services:

  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    labels:
      app-name: elasticsearch

  logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "5044:5044"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch
    labels:
      app-name: logstash

  kibana:
    build:
      context: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch
    labels:
      app-name: kibana
  
  filebeat:
    build:
      context: filebeat/
    volumes:
      - /var/lib/docker/containers/:/var/lib/docker/containers/
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - elk
    user: root
    depends_on:
      - logstash
    labels:
      app-name: filebeat
      foobar: snafu

networks:

  elk:
    driver: bridge
